### ISSUE TITLE
 University email validation limited (Unicamp)

### ISSUE THREAD

**Issue by pereirfe** [Unicaronas/Unicaronas#32]
The registration requires the Unicamp email to be in the format "LXXXXXX@dac.unicamp.br" or LXXXXXX@g.unicamp.br". Two minor problems arise from this:

- The regular expression use '.' on its definition, which matches any character. E.g.: a mail "x666666@ggunicamp.br" could be bought and used 

- Usually students receive more than one mail (specially post-grad). Those emails are not matchable by current regex. 
E.g: 
xxxxxxxxxxx@lrc.ic.unicamp.br -- Networks lab @IC
xxxxxxxxxxx@students.ic.unicamp.br -- students @IC
xxxxxxxxxxx@fee.unicamp.br -- students @feec

**Comment by Maronato** [comment]
Nice catch! This is actually pretty serious.

I only have one problem with allowing any email ending with .unicamp.br, which is something that is currently a problem and that I've been thinking of a way to fix: allowing people to create multiple accounts.

If we limit emails to the current two options, we can query the RA included in the email to verify identity and assert uniqueness. That, however, may not be possible with other subdomains that allow arbitrary email names.

Querying the RA is a weak fix since it may not apply to other Universities that we decide to support later on.

For me, the easiest solution would be to only allow one type of email per university, but I'd like to hear yours and others opinions on this.
